#!/usr/bin/env bash

if [ -z "$SAGE_LOCAL" ]; then
    echo >&2 "SAGE_LOCAL undefined ... exiting"
    echo >&2 "Maybe run 'sage --sh'?"
    exit 1
fi

cd src/c

$MAKE
if [ $? -ne 0 ]; then
    echo >&2 "Error building conjecturing suite."
    exit 1
fi

echo >&2 "Copying expressions..."
cp build/expressions $SAGE_LOCAL/bin/expressions
if [ $? -ne 0 ]; then
    echo >&2 "Error installing expressions."
    exit 1
fi
